version: "3.9"
services:
  deck:
    image: ghcr.io/hannahellis4242/tarot2/deck:latest
    ports:
      - "5000:5000"
  client:
    image: ghcr.io/hannahellis4242/tarot2/client:latest
    ports:
      - "80:8080"
