name: Docker Image CI - deck

on:
  push:
    paths:
      - "deck/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Build And Push deck Image
        run: |
          docker build ./deck --file deck/Dockerfile --tag ghcr.io/hannahellis4242/tarot2/deck:latest
          docker push ghcr.io/hannahellis4242/tarot2/deck:latest
