FROM node:alpine

WORKDIR /client
COPY ./client/package.json .
RUN npm i
COPY ./client/tsconfig .
COPY ./client/webpack.config.js .
COPY ./client/public public
COPY ./client/src src
RUN npm build

WORKDIR /web
RUN mv ../client/dist static
COPY package.json .
RUN npm i
COPY src src
RUN npm run build
CMD npm start